### ISSUE TITLE
Nice code presentation + suggestion

### ISSUE THREAD

**Issue by jericahuang** [ecburke/prj-rev-bwfs-dasmoto#3]
Both your HTML and CSS are nicely indented and organized. It makes it easier for reviewers like me to understand your code, and you too if you decide to look back on this code in the future. It's definitely worth the extra effort. Wonderful work! 👍 To improve its presentation further, consider adding comments to outline sections in your code! For example,
`<!--Paint-->`

**Comment by ecburke** [comment]
Done. Great suggestion.
