### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by jericahuang** [ecburke/prj-rev-bwfs-dasmoto#4]
Great job recreating the Dasmoto site! It looks exactly like the specification and your code accomplished it masterfully. Check out the minor issues I made note of for polishing things up under the hood! A general suggestion for improvement would be to make your code more readable by leaving comments in your code to outline sections or explain a piece of code. You're in a great position to succeed in this program. Keep up the great work! You have a lot to be proud of!

As a challenge, try adding a Google Font or tweaking the layout so that images are next to each paragraph. Based on your work here I think it's a challenge you're ready for!

**Comment by ecburke** [comment]
Thank you for the feedback! I revised the code and checked-out the reference articles you sent.  I'll keep these things in mind for future projects.
